In [1]:
import numpy as np

In [2]:
data=np.load("C:/Users/PC/Downloads/test.npy")
data

array([[[-1.1602267 , -3.9833636 , -2.3417685 , ..., -1.0595291 ,
         -0.4081105 , -2.7872818 ],
        [-2.6938355 , -5.005462  , -3.011996  , ...,  0.2615432 ,
         -0.20764044, -2.0945032 ],
        [-2.7431304 , -5.0512357 , -3.17253   , ...,  0.27626294,
         -0.06980276, -1.9828112 ],
        ...,
        [-0.15665434, -2.717404  , -2.74017   , ..., -1.1342764 ,
         -0.96800727, -4.253045  ],
        [-0.34845293, -2.6172612 , -2.6931324 , ..., -1.3665224 ,
         -0.9654854 , -4.9869184 ],
        [-1.9384375 , -0.2820665 , -2.179023  , ...,  0.61066127,
         -0.9630485 , -5.0735497 ]]], dtype=float32)

In [10]:
class PCA:
    def __init__(self,n_component):
        self.n_components=n_component
        self.components=None
        self.mean=None
    
    def fit(self,X):
        #sub mean
        self.mean=np.mean(X,axis=0)
        X=X-self.mean
        #cov
        cov=np.cov(X.T)

        #eigenVectors, Values
        eigenvectors,eigenvalues=np.linalg.eig(cov)

        #eigenvectors v=[:,i] column vector, transpose
        idxs=np.argsort(eigenvalues)[::-1]
        eigenvalues=eigenvalues[idxs]
        eigenvectors=eigenvectors[idxs]

        self.components = eigenvectors[:self.n_components]

    def transform(self,X):
        X= X-self.mean
        return np.dot(X,self.components.T)



In [11]:
def PCA_images(data,n_components):
    if len(data.shape)==3:
        h,w,c=data.shape
        reshape_data=data.reshape(h*w,c)
    else:
        reshape_data=data
        h,w=data.shape
        c=1

    pca=PCA(n_components)
    pca.fit(reshape_data)
    new_data=pca.transform(reshape_data)
    return new_data    

In [12]:
new_data = PCA_images(data,3)
print(new_data.shape)

(5184, 3)


In [13]:
print(new_data)

[[ 297.06565792  538.48365613 -119.95040991]
 [  23.61728764  308.73682708  219.02643672]
 [  65.78273011  313.46144657  256.73215582]
 ...
 [ 445.4543252   187.28555647 -236.39953247]
 [ 506.24601811   89.84368268 -186.91030982]
 [ 385.69294895   -3.46206853  -52.97467984]]


In [15]:
buddy=np.array([[[1,3,4,6],[3,54,78,8],[123,1,12,7]]])
print(buddy.shape)

(1, 3, 4)


In [21]:
new_buddy=PCA_images(buddy,2)
print(new_buddy.shape[:1])

(3,)
